sudo: false

language: c

matrix:
  include:
    - dist: xenial
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test     # For gcc 4.9, 5 and 7
          packages:
            - gcc-7
            - gfortran-7
            - zstd
            - exuberant-ctags
            - libnetcdf-dev 
    - osx_image: xcode11
      os: osx
      addons:
        homebrew:
        taps: homebrew/cask-versions
        casks: 
          - fftw
          - zstd
          - ctags
          - netcdf
      env: PATH=/usr/local/bin:$PATH
install:
    - mkdir build
    - cd build
    - |
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        cmake -DCMAKE_INSTALL_PREFIX=$HOME ..
      else
        # alias ctags='/usr/local/bin/ctags'
        brew install ctags
        which ctags
        cmake -DCMAKE_INSTALL_PREFIX=$HOME ..
      fi
    - make 
    - make install
script:
    - echo
